" --- Start Vundle --- "

filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'Lokaltog/vim-powerline'
Plugin 'scrooloose/nerdtree'
Plugin 'Yggdroot/indentLine'
Plugin 'jiangmiao/auto-pairs'
Plugin 'tell-k/vim-autopep8'
Plugin 'scrooloose/nerdcommenter'

call vundle#end()

filetype plugin indent on " 依檔案類型決定縮排 

" --- YouCompleteMe Setting ---"

let g:ycm_python_binary_path = '/Users/huangyue-lun/.pyenv/shims/python'

" let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
" let g:ycm_confirm_extra_conf=0
" set completeopt=longest,menu
" let g:ycm_path_to_python_interpreter='/Users/huangyue-lun/.pyenv/shims/python'
" let g:ycm_seed_identifiers_with_syntax=1
" let g:ycm_complete_in_comments=1
" let g:ycm_collect_identifiers_from_comments_and_strings = 0
" let g:ycm_min_num_of_chars_for_completion=2
" let g:ycm_autoclose_preview_window_after_completion=1
" let g:ycm_cache_omnifunc=0
" let g:ycm_complete_in_strings = 1
" autocmd InsertLeave * if pumvisible() == 0|pclose|endif
" inoremap <expr> <CR>       pumvisible() ? '<C-y>' : '\<CR>'
" inoremap <expr> <Down>     pumvisible() ? '\<C-n>' : '\<Down>'
" inoremap <expr> <Up>       pumvisible() ? '\<C-p>' : '\<Up>'
" inoremap <expr> <PageDown> pumvisible() ? '\<PageDown>\<C-p>\<C-n>' : '\<PageDown>'
" inoremap <expr> <PageUp>   pumvisible() ? '\<PageUp>\<C-p>\<C-n>' : '\<PageUp>'

" --- Setting --- "

syntax on

colorscheme molokai
let g:molokai_original = 1
let g:rehash256 = 1

set bg=dark
set t_Co=256
set ruler
set backspace=2
set modeline
set mouse=a        " 啟用游標選取及滾輪滑動
set hlsearch       " 搜尋高亮度
set showmode       " 模式提示
set showcmd        " 指令暫存提示
set history=50     " 保留50個歷史指令
set ai             " 自動對齊縮排
set tabstop=4      " 縮排間隔數
set shiftwidth=4   " 自動縮排間隔數
set expandtab      " tab轉換為space 
" set cindent        " 自動縮排 

" Key Mapping 自動補齊括號
" inoremap {<CR> {<CR>}<Esc>ko
" inoremap {{ {}<ESC>i
" inoremap ( ()<Esc>i
" inoremap ' ''<Esc>i
" inoremap [ []<Esc>i

set number
set cursorline
" 設定行號為粗體灰色
hi LineNr cterm=bold ctermfg=DarkGrey ctermbg=NONE
" 設定游標所在該行為粗體白色
hi CursorLineNr cterm=bold ctermfg=White ctermbg=NONE
